[project]
name = "rick-and-morty-api-testing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.6"
dependencies = [
    "pytest>=8.4.2",
    "requests>=2.32.5",
]
